apiVersion: v2
description: The fullstack of Cord Tools
name: cord-stack
version: "1.0.0-rc.10"
icon: https://irp.cdn-website.com/27aeb91f/dms3rep/multi/Cord-Logo-Stacked-57x57.png
home: https://github.com/cord-tools/helm-charts
sources:
  - https://github.com/cord-tools/
maintainers:
  - name: hoodoo-digital
    url: https://hoodoo.digital
    email: hello@hoodoo.digital
dependencies:
  - name: cord-api
    version: "1.0.0-rc.9"
    condition: cord-api.enabled
    repository: https://cord-tools.github.io/helm-charts
  - name: cord-api-v2
    version: "1.0.0-rc.3"
    condition: cord-api-v2.enabled
    repository: https://cord-tools.github.io/helm-charts
  - name: cord-ui
    version: "1.0.0-rc.3"
    condition: cord-ui.enabled
    repository: https://cord-tools.github.io/helm-charts
  - name: cord-proxy
    version: "1.0.0-rc.3"
    condition: cord-proxy.enabled
    repository: https://cord-tools.github.io/helm-charts
  - name: ingress-nginx
    version: ~3.22.0
    condition: ingress-nginx.enabled
    repository: https://kubernetes.github.io/ingress-nginx
  - name: kube-prometheus-stack
    version: ~13.3.0
    condition: kube-prometheus-stack.enabled
    repository: https://prometheus-community.github.io/helm-charts
