{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cord-api.fullname" . }}
  labels:
    {{- include "cord-api.labels" . | nindent 4 }}
rules:
  - apiGroups:
     - ""
    resources: 
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
     - ""
     - apps
     - batch
    resources:
      - configmaps
      - secrets
      - deployments
      - statefulsets
      - jobs
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
      - deletecollection
{{- end }}
