{{- if .Values.localFileStore.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cord-api.fullname" . }}-signing-key
  labels:
    {{- include "cord-api.labels" . | nindent 4 }}
data:
  signing.key: {{ .Values.localFileStore.signingKey | b64enc | quote }}
{{- end -}}
