apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cord-api.fullname" . }}
  labels:
    {{- include "cord-api.labels" . | nindent 4 }}
data:
  DB_PASSWORD: {{ .Values.mongodb.auth.password | default "" | b64enc | quote }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | default "" | b64enc | quote }}
{{- end }}
  {{- if .Values.internalAPIUser }}
  INTERNAL_API_USER: {{ .Values.internalAPIUser | b64enc | quote }}
  {{- else }}
  INTERNAL_API_USER: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.internalAPIPass }}
  INTERNAL_API_PASS: {{ .Values.internalAPIPass | b64enc | quote }}
  {{- else }}
  INTERNAL_API_PASS: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
