{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cord-api.serviceAccountName" . }}
  labels:
    {{- include "cord-api.labels" . | nindent 4 }}
{{- end }}
