{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cord-api.fullname" . }}-aem
  labels:
  {{- include "cord-api.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      cordToolsApp: aem
  endpoints:
    - port: prometheus-metrics
      interval: 1m
  podTargetLabels:
    - cordToolsAccount
    - cordToolsEnvironment
    - cordToolsInstanceType
{{- end }}
