apiVersion: v1
kind: Service
metadata:
  name: {{ include "cord-api.fullname" . }}
  labels:
  {{- include "cord-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.internalPort }}
      targetPort: http-internal
      protocol: TCP
      name: http-internal
  selector:
    {{- include "cord-api.selectorLabels" . | nindent 4}}
