{{- if and (index .Values "kube-prometheus-stack" "enabled") (index .Values "kube-prometheus-stack" "grafana" "enabled") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cord-stack.fullname" . }}-grafana-datasource
  labels:
    {{- if index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label" }}
    {{ index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label" }}: "1"
    {{- end }}
    {{- include "cord-stack.labels" . | nindent 4 }}
data:
  datasource-cordtools.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://{{ include "cord-stack.loki.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:3100
      access: proxy
      jsonData:
        timeField: time
        timeFormat: "iso8601"
        httpHeaderName1: 'X-Scope-OrgID'
        httpHeaderValue1: '1'
        httpMethod: POST
      version: 1
      editable: false
{{- end }}
