{{- if and (index .Values "kube-prometheus-stack" "enabled") (index .Values "kube-prometheus-stack" "grafana" "enabled") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cord-stack.fullname" . }}-grafana-datasource
  labels:
    {{- if index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label" }}
    {{ index .Values "kube-prometheus-stack" "grafana" "sidecar" "datasources" "label" }}: "1"
    {{- end }}
    {{- include "cord-stack.labels" . | nindent 4 }}
data:
  datasource-cordtools.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki-gateway:80
      access: proxy
      isDefault: true
      version: 1
      editable: true
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://{{ include "cord-stack.prometheus.fullname" . }}:{{ index .Values "kube-prometheus-stack" "prometheus" "service" "port" }}
      access: proxy
      isDefault: false
      editable: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
{{- end }}