apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cord-proxy.fullname" . }}
  labels:
    {{- include "cord-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cord-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cord-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: http-metrics
              containerPort: 9216
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /aem-cloud-static/health-check.txt
              port: http
          readinessProbe:
            httpGet:
              path: /aem-cloud-static/health-check.txt
              port: http
          env:
            - name: AEMCLOUD_API_URL
              {{- if .Values.aemcloudAPIUrl }}
              value: {{ .Values.aemcloudAPIUrl | quote }}
              {{- else }}
              value: "http://{{ include "cord-proxy.cord-api.fullname" . }}:8080"
              {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "cord-proxy.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
