apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cord-proxy.fullname" . }}
  labels:
    {{- include "cord-proxy.labels" . | nindent 4 }}
data:
  INTERNAL_API_USER: {{ .Values.internalAPIUser | b64enc }}
  INTERNAL_API_PASS: {{ .Values.internalAPIPass | b64enc }}
