apiVersion: v1
kind: Service
metadata:
  name: {{ include "cord-ui.fullname" . }}
  labels:
    {{- include "cord-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-cord
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: 9113
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "cord-ui.selectorLabels" . | nindent 4 }}
