{
 "title": "AEM",
 "tags": [
  "aem",
  "cord-tools"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(com_adobe_granite_replication_agent_Valid, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(com_adobe_granite_replication_agent_Valid{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "AEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "dtdurationms",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Last Backup Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_adobe_granite_Repository_BackupWasSuccessful{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Last Backup Created",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cordtools_backup_last_run_seconds_ago{account=\"$namespace\",exported_instance=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(com_adobe_granite_DISK_TOTAL_SPACE_Value{namespace=\"$namespace\",pod=\"$pod\"} - com_adobe_granite_DISK_USABLE_SPACE_Value{namespace=\"$namespace\",pod=\"$pod\"}) / com_adobe_granite_DISK_TOTAL_SPACE_Value{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptor Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(com_adobe_granite_OPEN_FILE_DESCRIPTOR_COUNT_Value{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Current # of Threads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Agent Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (com_adobe_granite_replication_agent_QueueBlocked{namespace=\"$namespace\",pod=\"$pod\"})"
    },
    {
     "expr": "sum by (id) (com_adobe_granite_replication_agent_Enabled{namespace=\"$namespace\",pod=\"$pod\"})"
    },
    {
     "expr": "sum by (id) (com_adobe_granite_replication_agent_QueuePaused{namespace=\"$namespace\",pod=\"$pod\"})"
    },
    {
     "expr": "sum by (id) (com_adobe_granite_replication_agent_Valid{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Agent Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_adobe_granite_replication_agent_QueueNumEntries{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(com_adobe_granite_requests_logging_granite_request_metrics_timer_Count{namespace=\"$namespace\",pod=\"$pod\"}[2m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "com_adobe_granite_requests_logging_granite_request_metrics_timer_50thPercentile{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "com_adobe_granite_requests_logging_granite_request_metrics_timer_75thPercentile{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "com_adobe_granite_requests_logging_granite_request_metrics_timer_99thPercentile{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Query Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(org_apache_jackrabbit_oak_QUERY_DURATION_Count{namespace=\"$namespace\",pod=\"$pod\"}[2m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Query Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_jackrabbit_oak_QUERY_DURATION_50thPercentile{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "org_apache_jackrabbit_oak_QUERY_DURATION_75thPercentile{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "org_apache_jackrabbit_oak_QUERY_DURATION_99thPercentile{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  { "title": "Sling Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_sling_queues_NumberOfActiveJobs{namespace=\"$namespace\",pod=\"$pod\",name=\"AllQueues\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "increase(org_apache_sling_queues_NumberOfFinishedJobs{namespace=\"$namespace\",pod=\"$pod\",name=\"AllQueues\"}[2m])",
     "legendFormat": "Finished"
    },
    {
     "expr": "increase(org_apache_sling_queues_NumberOfFailedJobs{namespace=\"$namespace\",pod=\"$pod\",name=\"AllQueues\"}[2m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "increase(org_apache_sling_queues_NumberOfCancelledJobs{namespace=\"$namespace\",pod=\"$pod\",name=\"AllQueues\"}[2m])",
     "legendFormat": "Cancelled"
    }
   ]
  }
 ]
}