{
 "title": "Apache/Dispatcher",
 "tags": [
  "dispatcher",
  "cord-tools"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(apache_up, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(apache_up{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(apache_up{pod=~\"$pod\"} == 1)",
     "legendFormat": "Apache Up"
    },
    {
     "expr": "scalar(count(apache_up{pod=~\"$pod\"} == 0))",
     "legendFormat": "Apache Down"
    }
   ]
  },
  {
   "title": "Current total kbytes sent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "Kilobytes Sent"
    }
   ]
  },
  {
   "title": "Current total apache accesses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache_accesses_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "Accesses"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_scoreboard{pod=~\"$pod\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{pod=~\"$pod\"}\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_cpuload{pod=~\"$pod\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}