{
 "title": "Cord Tools API v2",
 "tags": [ "cord-tools" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": "label_values(ruby_http_requests_total,service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{service=\"$service\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ruby_http_requests_total{service=\"$service\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SQL Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(increase(ruby_http_sql_duration_seconds[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(increase(ruby_http_sql_duration_seconds[1m]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(increase(ruby_http_sql_duration_seconds[1m]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(increase(ruby_http_duration_seconds[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(increase(ruby_http_duration_seconds[1m]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(increase(ruby_http_duration_seconds[1m]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Slowest Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, avg(increase(ruby_http_duration_seconds[2m])) by (controller, action)))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Top Requested Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(rate(ruby_http_requests_total[1m])) by (controller, action)))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  }
 ]
}