{
 "title": "Cord Tools API",
 "tags": [ "cord-tools" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(api_requests_total,service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Request Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_sum{service=\"$service\"}[1m])) by (code) / sum(increase(request_duration_seconds_count{service=\"$service\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{service=\"$service\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "In Flight Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(in_flight_requests{service=\"$service\"})"
    }
   ]
  }
 ]
}