apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cord-api-v2.fullname" . }}
  labels:
    {{- include "cord-api-v2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cord-api-v2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cord-api-v2.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cord-api-v2.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: db-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.dbMigrateArgs }}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /bin/bash
            - -c
          env:
            - name: DB_HOST
              value: {{ template "cord-api-v2.postgresql.fullname" . }}
            - name: ENABLE_PROMETHEUS
              value: "false"
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            {{- range $key, $value := .Values.config }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "cord-api-v2.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ template "cord-api-v2.postgresql.fullname" . }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: ENABLE_PROMETHEUS
              value: {{ .Values.metrics.enabled | quote }}
            - name: INTERNAL_API_USER
              value: {{ .Values.internalAPIUser | quote }}
          {{- range $key, $value := .Values.config }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "cord-api-v2.fullname" . }}
          livenessProbe:
            httpGet:
              path: /users/sign_in
              port: http
          readinessProbe:
            httpGet:
              path: /users/sign_in
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.metrics.enabled }}
        - name: prometheus-metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "prometheus_exporter"]
          ports:
            - name: http-metrics
              containerPort: 9394
              protocol: TCP
      {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
