apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cord-api-v2.fullname" . }}
  labels:
    {{- include "cord-api-v2.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.postgresPassword | b64enc }}
  INTERNAL_API_PASS: {{ .Values.internalAPIPass | b64enc }}
  {{- range $key, $secret := .Values.secrets }}
  {{ $key }}: {{ $secret | b64enc }}
  {{- end }}
