{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cord-api-v2.fullname" . }}
  labels:
    {{- include "cord-api-v2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cord-api-v2.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
{{- end }}
